// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: message.sql

package model

import (
	"context"
)

const createDirectMessage = `-- name: CreateDirectMessage :exec
INSERT INTO direct_message (
  receiver_id, message_id
) VALUES (
  ?, ?
)
`

type CreateDirectMessageParams struct {
	ReceiverID int64
	MessageID  int64
}

func (q *Queries) CreateDirectMessage(ctx context.Context, arg CreateDirectMessageParams) error {
	_, err := q.exec(ctx, q.createDirectMessageStmt, createDirectMessage, arg.ReceiverID, arg.MessageID)
	return err
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO message (
  sender_id, content
) VALUES (
  ?, ?
)
RETURNING id
`

type CreateMessageParams struct {
	SenderID int64
	Content  string
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (int64, error) {
	row := q.queryRow(ctx, q.createMessageStmt, createMessage, arg.SenderID, arg.Content)
	var id int64
	err := row.Scan(&id)
	return id, err
}
