root = "."
tmp_dir = "bin"

[build]
  bin = "./bin/main"
  cmd = "go run github.com/a-h/templ/cmd/templ@latest fmt view && make build"
  delay = 1000
  exclude_dir = ["tmp", "public"]
  exclude_regex = [".*_templ.go"]
  exclude_unchanged = false
  follow_symlink = false
  include_ext = ["go", "tpl", "tmpl", "templ", "html", "css"]
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = true

[color]
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = true
